title: Project

columns:

  - width: 1/2
    sections:

      project:
        type: files
        template: project
        layout: cards
        size: tiny
        image:
          ratio: 1/1
          cover: true

  - width: 1/2
    sections:

      content:
        type: fields
        fields:

          text:
            extends: fields/text

          textPosition:
            label: Text Position
            type: select
            placeholder: aside
            options:
              - above

      files:
        extends: sections/files
        template: default

      metadata:
        type: fields
        fields:

          client:
            label: Client
            type: text
            icon: bookmark

          role:
            label: Role
            type: text
            icon: user
            help: e.g. "Assistant Chief Lighting Technician" or "Horse Wrangler"

          date:
            label: Date
            type: text
            icon: calendar
            help: e.g. "Feb 14, 2020" or "Summer 1979"

          website:
            label: Website
            type: url
            icon: url
